// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly FIREBASE_CONFIG: string;
  readonly BASE_URL: string;
  readonly CITY_BASE_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
