import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from "next/head";
 

const MyApp = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <title>Dashboard Project</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </>
);

export default MyApp;
