/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActiveTripDataResponse } from './models/ActiveTripDataResponse';
export type { AggregatedRequest } from './models/AggregatedRequest';
export type { AreaPriceDestinationType } from './models/AreaPriceDestinationType';
export type { AreaPriceDto } from './models/AreaPriceDto';
export type { AreaPriceRequestTypeDto } from './models/AreaPriceRequestTypeDto';
export type { ArriveAtDestinationRequest } from './models/ArriveAtDestinationRequest';
export type { BaseNightPeriodsDto } from './models/BaseNightPeriodsDto';
export type { BaseRoleDto } from './models/BaseRoleDto';
export type { BasicResponse } from './models/BasicResponse';
export type { BlockedServantDto } from './models/BlockedServantDto';
export type { BlockUserRequest } from './models/BlockUserRequest';
export type { CancelReasonDto } from './models/CancelReasonDto';
export type { CancelReasonResponse } from './models/CancelReasonResponse';
export type { CancelReasonTranslationDto } from './models/CancelReasonTranslationDto';
export type { ChangeDestinationRequestDto } from './models/ChangeDestinationRequestDto';
export { ChangeDestinationRequestStatus } from './models/ChangeDestinationRequestStatus';
export type { ChangeDestinationRequestStatusLogDto } from './models/ChangeDestinationRequestStatusLogDto';
export type { CheckDiscountCodeResponse } from './models/CheckDiscountCodeResponse';
export type { ClientCancelTaskRequest } from './models/ClientCancelTaskRequest';
export type { ClientDiscountCodeResponse } from './models/ClientDiscountCodeResponse';
export type { ClientGetCancelReasonResponse } from './models/ClientGetCancelReasonResponse';
export type { CommissionDto } from './models/CommissionDto';
export type { CommissionPeriodDto } from './models/CommissionPeriodDto';
export type { CountryDto } from './models/CountryDto';
export type { CountryTranslation } from './models/CountryTranslation';
export type { CreateAreaPriceRequest } from './models/CreateAreaPriceRequest';
export type { CreateCommissionPeriodRequest } from './models/CreateCommissionPeriodRequest';
export type { CreateFavoriteRequest } from './models/CreateFavoriteRequest';
export type { CreateOrUpdatePlaqueRequest } from './models/CreateOrUpdatePlaqueRequest';
export type { CreateServantRequest } from './models/CreateServantRequest';
export type { CreateServantResponse } from './models/CreateServantResponse';
export type { CreateServiceRequest } from './models/CreateServiceRequest';
export type { CreateServiceTypeRequest } from './models/CreateServiceTypeRequest';
export type { CreateUpdateCancelReasonRequest } from './models/CreateUpdateCancelReasonRequest';
export type { CreateUpdateDiscountCodeRequest } from './models/CreateUpdateDiscountCodeRequest';
export type { CreateUpdateDiscountOfferRequest } from './models/CreateUpdateDiscountOfferRequest';
export type { CreateUpdateServiceAppConfigurationRequest } from './models/CreateUpdateServiceAppConfigurationRequest';
export type { CreateUpdateTaskCancellationPenalizeRequest } from './models/CreateUpdateTaskCancellationPenalizeRequest';
export type { CreateUpdateTaskCancellationPolicyMeasurementRequest } from './models/CreateUpdateTaskCancellationPolicyMeasurementRequest';
export type { CreateUpdateTaskCancellationPolicyRequest } from './models/CreateUpdateTaskCancellationPolicyRequest';
export type { CreateUpdateTaskRatingAspectRequest } from './models/CreateUpdateTaskRatingAspectRequest';
export type { CreateUpdateTaskReportActionRequest } from './models/CreateUpdateTaskReportActionRequest';
export type { CreateUpdateTaskReportDefinedProblemRequest } from './models/CreateUpdateTaskReportDefinedProblemRequest';
export type { CreateUpdateTaskReportDefinedProblemTranslationRequest } from './models/CreateUpdateTaskReportDefinedProblemTranslationRequest';
export type { CreateVehicleRequest } from './models/CreateVehicleRequest';
export { DayOfWeek } from './models/DayOfWeek';
export type { DestinationClientDto } from './models/DestinationClientDto';
export type { DestinationDto } from './models/DestinationDto';
export type { DestinationLogDto } from './models/DestinationLogDto';
export type { DestinationRouteDto } from './models/DestinationRouteDto';
export { DestinationRouteType } from './models/DestinationRouteType';
export { DestinationStatusEnum } from './models/DestinationStatusEnum';
export { DestinationType } from './models/DestinationType';
export type { Direction } from './models/Direction';
export type { DiscountCodeDto } from './models/DiscountCodeDto';
export type { DiscountCodeDtoPagination } from './models/DiscountCodeDtoPagination';
export { DiscountCodeSearchFieldEnum } from './models/DiscountCodeSearchFieldEnum';
export type { DiscountCodeStepDto } from './models/DiscountCodeStepDto';
export type { DiscountCodeStepRequest } from './models/DiscountCodeStepRequest';
export type { DiscountCodeStepResponse } from './models/DiscountCodeStepResponse';
export type { DiscountDto } from './models/DiscountDto';
export type { DiscountOfferDto } from './models/DiscountOfferDto';
export type { DiscountOfferDtoPagination } from './models/DiscountOfferDtoPagination';
export type { DiscountOfferRequirement } from './models/DiscountOfferRequirement';
export type { DiscountOfferRequirementRequest } from './models/DiscountOfferRequirementRequest';
export type { DiscountOfferStep } from './models/DiscountOfferStep';
export type { DiscountOfferStepRequest } from './models/DiscountOfferStepRequest';
export type { DiscountPeriodsDto } from './models/DiscountPeriodsDto';
export { DiscountStepTimeFrame } from './models/DiscountStepTimeFrame';
export { DiscountType } from './models/DiscountType';
export type { EstimatedServiceResponse } from './models/EstimatedServiceResponse';
export type { EstimateRequestForPanelResult } from './models/EstimateRequestForPanelResult';
export type { FavoriteDto } from './models/FavoriteDto';
export { FavoriteType } from './models/FavoriteType';
export type { FileUpload } from './models/FileUpload';
export { Gender } from './models/Gender';
export { GetAllUserBlockHistoryType } from './models/GetAllUserBlockHistoryType';
export type { GetBaseRolesResponse } from './models/GetBaseRolesResponse';
export type { GetEstimatedTaskRequest } from './models/GetEstimatedTaskRequest';
export type { GetEstimatedTaskResponse } from './models/GetEstimatedTaskResponse';
export type { GetMemberCountResponse } from './models/GetMemberCountResponse';
export type { GetPanelEstimateRequestModel } from './models/GetPanelEstimateRequestModel';
export type { GetPoliciesResponse } from './models/GetPoliciesResponse';
export type { GetRequestCountResponse } from './models/GetRequestCountResponse';
export type { GetServantClientStatisticsResult } from './models/GetServantClientStatisticsResult';
export type { GetServantCountResponse } from './models/GetServantCountResponse';
export type { GetServantRouteInTask } from './models/GetServantRouteInTask';
export type { GetServantServiceConfigurationResult } from './models/GetServantServiceConfigurationResult';
export type { GetServantServices } from './models/GetServantServices';
export type { GetServantSessionItem } from './models/GetServantSessionItem';
export type { GetServantSessions } from './models/GetServantSessions';
export type { GetServantSessionSummery } from './models/GetServantSessionSummery';
export type { GetServicesClientResponse } from './models/GetServicesClientResponse';
export type { GetSubscribedServantServiceTypesResponse } from './models/GetSubscribedServantServiceTypesResponse';
export type { GetTaskCountResponse } from './models/GetTaskCountResponse';
export type { GetTaskDetailClientResult } from './models/GetTaskDetailClientResult';
export type { GetUserByPhoneNumberResponse } from './models/GetUserByPhoneNumberResponse';
export type { GetUserRolesResponse } from './models/GetUserRolesResponse';
export type { GetUsersAdminOptions } from './models/GetUsersAdminOptions';
export type { GetUsersByIdsResponse } from './models/GetUsersByIdsResponse';
export type { HeatMapConfiguration } from './models/HeatMapConfiguration';
export type { HeatMapDataResult } from './models/HeatMapDataResult';
export { HeatMapType } from './models/HeatMapType';
export type { HelpTranslationDto } from './models/HelpTranslationDto';
export { Language } from './models/Language';
export type { ListAggregatedRequestResult } from './models/ListAggregatedRequestResult';
export type { ListAggregatedRequestResultPagination } from './models/ListAggregatedRequestResultPagination';
export type { ListCanceledTaskResult } from './models/ListCanceledTaskResult';
export type { ListCanceledTaskResultPagination } from './models/ListCanceledTaskResultPagination';
export { ListDiscountUsageDiscountType } from './models/ListDiscountUsageDiscountType';
export type { ListRequestResult } from './models/ListRequestResult';
export type { ListRequestResultPagination } from './models/ListRequestResultPagination';
export type { ListServantsPerformancesResponse } from './models/ListServantsPerformancesResponse';
export type { ListServantsPerformancesResponsePagination } from './models/ListServantsPerformancesResponsePagination';
export type { ListServantsResult } from './models/ListServantsResult';
export type { ListServantsResultPagination } from './models/ListServantsResultPagination';
export type { ListServiceHourlyStatisticResult } from './models/ListServiceHourlyStatisticResult';
export type { ListServiceHourlyStatisticResultPagination } from './models/ListServiceHourlyStatisticResultPagination';
export type { ListTaskClientResult } from './models/ListTaskClientResult';
export type { ListTaskReportClientResult } from './models/ListTaskReportClientResult';
export type { ListTaskReportResult } from './models/ListTaskReportResult';
export type { ListTaskReportResultPagination } from './models/ListTaskReportResultPagination';
export type { ListTaskResult } from './models/ListTaskResult';
export type { ListTaskResultPagination } from './models/ListTaskResultPagination';
export { ListVehicleRequestFilterField } from './models/ListVehicleRequestFilterField';
export type { LiveTaskStats } from './models/LiveTaskStats';
export type { LngLat } from './models/LngLat';
export type { LocationPoint } from './models/LocationPoint';
export type { ManageTaskRequest } from './models/ManageTaskRequest';
export type { MemberDto } from './models/MemberDto';
export type { MemberPaymentTypeDto } from './models/MemberPaymentTypeDto';
export type { MemberResponse } from './models/MemberResponse';
export type { MonthlyChartResponse } from './models/MonthlyChartResponse';
export type { NewRequestAlertServantMessage } from './models/NewRequestAlertServantMessage';
export type { NewRequestModel } from './models/NewRequestModel';
export type { NightPeriod } from './models/NightPeriod';
export type { NotifyServantPreferenceDto } from './models/NotifyServantPreferenceDto';
export type { PanelCreateRequestForClientModel } from './models/PanelCreateRequestForClientModel';
export type { PassengersReport } from './models/PassengersReport';
export { PaymentType } from './models/PaymentType';
export type { PeriodRequest } from './models/PeriodRequest';
export type { PlaqueDetailDto } from './models/PlaqueDetailDto';
export type { PolicyDto } from './models/PolicyDto';
export { PolicyType } from './models/PolicyType';
export type { PostChangeDestinationRequest } from './models/PostChangeDestinationRequest';
export type { PostNewRequest } from './models/PostNewRequest';
export type { PostRole } from './models/PostRole';
export type { PostServantBlockRequest } from './models/PostServantBlockRequest';
export type { PutBaseRole } from './models/PutBaseRole';
export type { PutChangeDestinationRequest } from './models/PutChangeDestinationRequest';
export type { PutRole } from './models/PutRole';
export type { PutServantBlockRequest } from './models/PutServantBlockRequest';
export type { PutUserRolesRequest } from './models/PutUserRolesRequest';
export type { RankedServantByTaskReport } from './models/RankedServantByTaskReport';
export type { RankedServantByTaskReportPagination } from './models/RankedServantByTaskReportPagination';
export type { RateTaskAspectRequest } from './models/RateTaskAspectRequest';
export type { RateTaskRequest } from './models/RateTaskRequest';
export type { RegionDto } from './models/RegionDto';
export type { RegionTranslation } from './models/RegionTranslation';
export type { ReportTaskRequest } from './models/ReportTaskRequest';
export type { RequestAlertDto } from './models/RequestAlertDto';
export { RequestAlertStatus } from './models/RequestAlertStatus';
export type { RequestDto } from './models/RequestDto';
export type { RequestReport } from './models/RequestReport';
export type { RequestServantResponse } from './models/RequestServantResponse';
export type { RequestServantResponsePagination } from './models/RequestServantResponsePagination';
export { RequestStatusEnum } from './models/RequestStatusEnum';
export { RequestType } from './models/RequestType';
export { RequestTypeEnum } from './models/RequestTypeEnum';
export type { ReviewTaskRequest } from './models/ReviewTaskRequest';
export type { RoleDto } from './models/RoleDto';
export type { RoleDtoPagination } from './models/RoleDtoPagination';
export { RoleType } from './models/RoleType';
export type { RouteToClientUpdateMessage } from './models/RouteToClientUpdateMessage';
export type { RoutingRequest } from './models/RoutingRequest';
export type { ServantAlertModel } from './models/ServantAlertModel';
export type { ServantDeviceDto } from './models/ServantDeviceDto';
export { ServantDeviceType } from './models/ServantDeviceType';
export type { ServantDto } from './models/ServantDto';
export type { ServantHourlyStatsResponse } from './models/ServantHourlyStatsResponse';
export type { ServantMiniInfo } from './models/ServantMiniInfo';
export type { ServantOnlineHistoryResponse } from './models/ServantOnlineHistoryResponse';
export type { ServantPerformanceResponse } from './models/ServantPerformanceResponse';
export type { ServantScoreDto } from './models/ServantScoreDto';
export { ServantSearchFieldEnum } from './models/ServantSearchFieldEnum';
export type { ServantStatisticDto } from './models/ServantStatisticDto';
export type { ServantStats } from './models/ServantStats';
export type { ServantStatusDto } from './models/ServantStatusDto';
export { ServantStatusEnum } from './models/ServantStatusEnum';
export type { ServantStatusLogDto } from './models/ServantStatusLogDto';
export type { ServantTaskPoint } from './models/ServantTaskPoint';
export type { ServantUpdateLocationRequest } from './models/ServantUpdateLocationRequest';
export type { ServantUpdateTaskRequest } from './models/ServantUpdateTaskRequest';
export type { ServantWalletLoanThresholdActionRequest } from './models/ServantWalletLoanThresholdActionRequest';
export { ServantWalletLoanThresholdDirection } from './models/ServantWalletLoanThresholdDirection';
export type { ServiceAppConfigurationDto } from './models/ServiceAppConfigurationDto';
export type { ServiceDto } from './models/ServiceDto';
export type { ServiceParamsDto } from './models/ServiceParamsDto';
export type { ServiceSettingsDto } from './models/ServiceSettingsDto';
export type { ServiceTypeDto } from './models/ServiceTypeDto';
export type { ServiceTypeTranslationDto } from './models/ServiceTypeTranslationDto';
export type { ServiceTypeTranslationRequest } from './models/ServiceTypeTranslationRequest';
export type { StartMonitoringResponse } from './models/StartMonitoringResponse';
export { StaticTypeEnum } from './models/StaticTypeEnum';
export type { TaskCancellationPenalizeDto } from './models/TaskCancellationPenalizeDto';
export type { TaskCancellationPenalizeTranslationDto } from './models/TaskCancellationPenalizeTranslationDto';
export { TaskCancellationPenalizeType } from './models/TaskCancellationPenalizeType';
export { TaskCancellationPenaltyType } from './models/TaskCancellationPenaltyType';
export type { TaskCancellationPolicyDto } from './models/TaskCancellationPolicyDto';
export type { TaskCancellationPolicyMeasurementDto } from './models/TaskCancellationPolicyMeasurementDto';
export { TaskCancellationPolicyMeasurementType } from './models/TaskCancellationPolicyMeasurementType';
export type { TaskDetailLog } from './models/TaskDetailLog';
export type { TaskDetailResult } from './models/TaskDetailResult';
export type { TaskInvoice } from './models/TaskInvoice';
export type { TaskRatingAspectDto } from './models/TaskRatingAspectDto';
export type { TaskRatingAspectTranslationDto } from './models/TaskRatingAspectTranslationDto';
export type { TaskRatingAspectTranslationRequest } from './models/TaskRatingAspectTranslationRequest';
export type { TaskReportActionDto } from './models/TaskReportActionDto';
export type { TaskReportActionsTakenDto } from './models/TaskReportActionsTakenDto';
export type { TaskReportActionTranslationDto } from './models/TaskReportActionTranslationDto';
export type { TaskReportDefinedProblemDto } from './models/TaskReportDefinedProblemDto';
export type { TaskReportDefinedProblemTranslationDto } from './models/TaskReportDefinedProblemTranslationDto';
export type { TaskReportDetail } from './models/TaskReportDetail';
export type { TaskReportDetailedActionsTaken } from './models/TaskReportDetailedActionsTaken';
export type { TaskRouteDto } from './models/TaskRouteDto';
export { TaskRouteType } from './models/TaskRouteType';
export { TaskStatusEnum } from './models/TaskStatusEnum';
export type { TaskStatusLogDto } from './models/TaskStatusLogDto';
export type { TaskStopLogDetail } from './models/TaskStopLogDetail';
export type { TextTranslation } from './models/TextTranslation';
export type { TextTranslationLanguage } from './models/TextTranslationLanguage';
export { TimeFrame } from './models/TimeFrame';
export type { TimeSpan } from './models/TimeSpan';
export type { TranslationRequest } from './models/TranslationRequest';
export type { TranslationValue } from './models/TranslationValue';
export type { TripStatusDetail } from './models/TripStatusDetail';
export type { TripStatusDto } from './models/TripStatusDto';
export { TripStatusEnum } from './models/TripStatusEnum';
export type { UpdateAreaPriceOrderRequest } from './models/UpdateAreaPriceOrderRequest';
export type { UpdateAreaPriceRequest } from './models/UpdateAreaPriceRequest';
export type { UpdateCommissionRequest } from './models/UpdateCommissionRequest';
export type { UpdateNotifyServantPreferenceRequest } from './models/UpdateNotifyServantPreferenceRequest';
export type { UpdateServantRequest } from './models/UpdateServantRequest';
export type { UpdateServantServiceConfigurationRequest } from './models/UpdateServantServiceConfigurationRequest';
export type { UpdateServantWalletLoanThresholdRequest } from './models/UpdateServantWalletLoanThresholdRequest';
export type { UpdateServiceParamsRequest } from './models/UpdateServiceParamsRequest';
export type { UpdateServiceRequest } from './models/UpdateServiceRequest';
export type { UpdateServiceSettingsRequest } from './models/UpdateServiceSettingsRequest';
export type { UpdateServiceTypeRequest } from './models/UpdateServiceTypeRequest';
export type { UpdateTaskCancellationPolicyOrderRequest } from './models/UpdateTaskCancellationPolicyOrderRequest';
export type { UpdateTaskReportActionOrderRequest } from './models/UpdateTaskReportActionOrderRequest';
export type { UpdateTaskReportRequest } from './models/UpdateTaskReportRequest';
export type { UpdateTranslationRequest } from './models/UpdateTranslationRequest';
export type { UpdateVehicleDetailRequest } from './models/UpdateVehicleDetailRequest';
export type { UpdateVehicleRequest } from './models/UpdateVehicleRequest';
export type { UpsertHeatMapConfigRequest } from './models/UpsertHeatMapConfigRequest';
export type { UserBlockDto } from './models/UserBlockDto';
export type { UserBlockDtoPagination } from './models/UserBlockDtoPagination';
export type { UserDto } from './models/UserDto';
export type { UserDtoPagination } from './models/UserDtoPagination';
export type { UserMiniDto } from './models/UserMiniDto';
export type { UserMiniDtoPagination } from './models/UserMiniDtoPagination';
export { UserSearchFieldEnum } from './models/UserSearchFieldEnum';
export type { UserTaskInvoice } from './models/UserTaskInvoice';
export type { VehicleDetailDto } from './models/VehicleDetailDto';
export type { VehicleDto } from './models/VehicleDto';
export type { VehicleDtoPagination } from './models/VehicleDtoPagination';
export { WalletLoanThresholdActionType } from './models/WalletLoanThresholdActionType';

export { AaService } from './services/AaService';
export { BaseRolesService } from './services/BaseRolesService';
export { CancelReasonService } from './services/CancelReasonService';
export { ChartService } from './services/ChartService';
export { DestinationService } from './services/DestinationService';
export { DiscountCodeService } from './services/DiscountCodeService';
export { DiscountOffersService } from './services/DiscountOffersService';
export { FavoriteService } from './services/FavoriteService';
export { HeatMapService } from './services/HeatMapService';
export { MapService } from './services/MapService';
export { MemberService } from './services/MemberService';
export { PassengersService } from './services/PassengersService';
export { PolicyService } from './services/PolicyService';
export { RequestService } from './services/RequestService';
export { RolesService } from './services/RolesService';
export { ServantService } from './services/ServantService';
export { ServantBlockService } from './services/ServantBlockService';
export { ServantDeviceService } from './services/ServantDeviceService';
export { ServantSessionsService } from './services/ServantSessionsService';
export { ServiceService } from './services/ServiceService';
export { ServiceAppConfigurationService } from './services/ServiceAppConfigurationService';
export { ServiceAreaPriceService } from './services/ServiceAreaPriceService';
export { ServiceTypeService } from './services/ServiceTypeService';
export { TaskService } from './services/TaskService';
export { TaskCancellationPenalizeService } from './services/TaskCancellationPenalizeService';
export { TaskCancellationPolicyService } from './services/TaskCancellationPolicyService';
export { TaskManagerService } from './services/TaskManagerService';
export { TaskRatingService } from './services/TaskRatingService';
export { TaskRatingAspectService } from './services/TaskRatingAspectService';
export { TaskReportService } from './services/TaskReportService';
export { TaskReportActionService } from './services/TaskReportActionService';
export { TaskReportDefinedProblemService } from './services/TaskReportDefinedProblemService';
export { TranslationService } from './services/TranslationService';
export { UserService } from './services/UserService';
export { UserBlockService } from './services/UserBlockService';
export { VehicleService } from './services/VehicleService';
